// This is a collection of job names, barriers, and other story elements to make our randomly generated people feel
// real.
export default {
  barriers: {
    'non-native-speaker': "'s first language isn't English and there's a concern that technical and legal terms of benefits won't be understood properly.",
    'no-personal-vehicle': " doesn't have a car. The family does all its transportation via public transport.",
    'welfare-bias': " believes that benefits are handouts for those that 'are too lazy to pick themselves up by their bootstraps.'",
    'undocumented-immigrant': " hasn't completed the process to become a US citizen. There's a fear that the family will be deported if they apply.",
    'technical-barrier': " doesn't know how to use a computer."
  },
  jobs: [
    "mechanic",
    "bank teller",
    "administrative assistant",
    "gas station attendant",
    "farmhand",
    "electronics store clerk",
    "cashier",
    "piano teacher",
    "gym teacher",
    "custodian",
    "security guard",
    "club bouncer",
    "bartender",
    "waiter",
    "hotel desk clerk",
    "call center representative",
    "crossing guard",
    "bus driver",
    "commercial trucker",
    "teacher's assistant",
    "receptionist",
    "drive-thru cashier",
    "pet groomer",
    "painter",
    "musician",
    "stand-up comic",
    "salesperson",
    "car wash attendant",
    "school nurse",
    "fitness trainer",
    "corporate security officer",
    "fry cook",
    "barista",
    "tattoo artist",
    "street musician",
    "repossession specialist",
    "parking lot attendant",
    "notary",
    "exterminator",
    "author",
    "artist",
    "theme park attendant",
    "printer",
    "forklift operator",
    "telemarketer",
    "call center supervisor",
    "fast food supervisor",
    "bar back",
    "general manager",
    "lead bank teller",
    "lead mechanic",
    "custodial supervisor",
    "groundskeeper",
    "lifeguard"
  ]
}