// This is a collection of job names, barriers, and other story elements to make our randomly generated people feel
// real.
import {Barrier} from './Barrier'

export default {
  barriers: [
    new Barrier('non-native-speaker', "'s first language isn't English and there's a concern that technical and legal terms of benefits won't be understood properly."),
    new Barrier('no-personal-vehicle', " doesn't have a car. The family does all its transportation via public transport."),
    new Barrier('welfare-bias', " believes that benefits are handouts for those that 'are too lazy to pick themselves up by their bootstraps.'"),
    new Barrier('undocumented-immigrant', " hasn't completed the process to become a US citizen. There's a fear that the family will be deported if they apply."),
    new Barrier('technical-barrier', " doesn't know how to use a computer.")
  ],
  jobs: [
    //Complete the sentence: "They currently work as ..."
    "a mechanic",
    "a bank teller",
    "an administrative assistant",
    "a gas station attendant",
    "a farmhand",
    "an electronics store clerk",
    "a cashier",
    "a piano teacher",
    "a gym teacher",
    "a custodian",
    "a security guard",
    "a club bouncer",
    "a bartender",
    "a waiter",
    "a hotel desk clerk",
    "a call center representative",
    "a crossing guard",
    "a bus driver",
    "a commercial trucker",
    "a teacher's assistant",
    "a receptionist",
    "a drive-thru cashier",
    "a pet groomer",
    "a painter",
    "a musician",
    "a stand-up comic",
    "a salesperson",
    "a car wash attendant",
    "a school nurse",
    "a fitness trainer",
    "a corporate security officer",
    "a fry cook",
    "a barista",
    "a tattoo artist",
    "a street musician",
    "a repossession specialist",
    "a parking lot attendant",
    "a notary",
    "an exterminator",
    "an author",
    "an artist",
    "a theme park attendant",
    "a printer",
    "a forklift operator",
    "a telemarketer",
    "a call center supervisor",
    "a fast food supervisor",
    "a bar back",
    "a general manager",
    "a lead bank teller",
    "a lead mechanic",
    "a custodial supervisor",
    "a groundskeeper",
    "a lifeguard"
  ]
}